# Generated by Django 2.1 on 2019-01-28 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_auto_20190128_1819'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-date_created'], 'verbose_name': 'Comment', 'verbose_name_plural': 'Comments'},
        ),
    ]
